### PR TITLE
feat: Auto router implemented (Navigator 2.0) & nstack upgraded

### PR DESCRIPTION
**Pull request by atiqmlbd**

### CODE REVIEW

**Review by pedromassango — APPROVED** [review]
LGTM

**Comment by markusrubey** [comment]
More team members should have a look at this. Idea currently is to have another PR with https://pub.dev/packages/go_router for comparison. Then we make a decision.

**Comment by atiqmlbd** [comment]
One of the main benefits of Auto Router is the automatic generation of Routes along with Parameters, so we will get compile time safety rather than run time error in terms of parameter passing between routes

**Comment by atiqmlbd** [comment]
typed routing is yet to be available in go_router 
https://gorouter.dev/typed-routing

**Comment by johsoe** [comment]
I think `AutoRoute` is a good candidate for solving navigation.

I would like to discuss the use of `AppNavigator` though. `AutoRoute` exposes the router via context extensions and we are also passing it along via `GetIt`. 

@atiqmlbd  What is the main argumentation behind the class? As I remember it from HeroesOfWork, we ended up moving fairly UI specific navigation out to a central location with no context as to why.

**Comment by atiqmlbd** [comment]
@johsoe it's used to hide all the internal logic of the router ( parameter mapping, dynamic routing based on some condition, default values) and gives flexibility on unit testing. With the help of app navigator we can move to different routers without modifying any code in the UI layer  if required

**Comment by johsoe** [comment]
> 

Ah! All good points 👍

**Review by AbbasMathiew — APPROVED** [review]

**Pull request merged**
