### PR TITLE
fix: Use monstarlab_lints : :

### PR DESCRIPTION
**Pull request by nivisi**

### CODE REVIEW

**Comment by hassan-saleh-ml** [comment]
@nivisi looks like there's a typo in one of the freezed classes

**Comment by utpal-barman** [comment]
just fyi that typo is fixed in https://github.com/monstar-lab-oss/flutter-template/pull/135

**Comment by utpal-barman** [comment]
looks like it has some conflicts in pubspec and some analyzer issue @nivisi

**Comment by nivisi** [comment]
@utpal-barman resolved boss

**Review by utpal-barman — APPROVED** [review]
✅

**Pull request merged**
