### PR TITLE
feat: mason - usecase bricks 

### PR DESCRIPTION
**Pull request by martinloesethjensen**
This PR contains custom bricks for: 

- `UseCase`
- `OutputUseCase`
- `StreamUseCase`
- `StreamOutputUseCase`
- `FutureUseCase`
- `FutureOutputUseCase`

### CODE REVIEW

**Comment by AbbasMathiew** [comment]
Hmm the idea I had with mason is that we create a separate repo for all the bricks that we create and install them globally, but seeing this now is making me double think that what do you think @martinloesethjensen 

P.S we also need documentation per brick about how to install and what is does etc

**Comment by AbbasMathiew** [comment]
@martinloesethjensen you can also use `// coverage:ignore-file` at the top of the file to omit it from coverage

**Comment by martinloesethjensen** [comment]
@AbbasMathiew ah so you mean kind of how they have with [brickhub](https://brickhub.dev/) 😄

**Comment by martinloesethjensen** [comment]
I will update the bricks README.md 😄

**Comment by martinloesethjensen** [comment]
@AbbasMathiew I could just exclude the `bricks/**` from analysis and then it was all good ;)

**Comment by AbbasMathiew** [comment]
last thing, if the brick code is updated the user has to reinstall the brick right?

**Comment by AbbasMathiew** [comment]
> @AbbasMathiew ah so you mean kind of how they have with [brickhub](https://brickhub.dev/) 😄

Ohhh nice, that was what felix was talking about all those months ago, should be more active on twitter 😆

**Comment by martinloesethjensen** [comment]
@AbbasMathiew If the brick code is local then I don't think that would be the case. I think if we change the folder structure for where the brick is located then, yes 😄 

I haven't tried with having a brick on a github repo and use it from there. 

I saw that people would be able to [publish to brickhub](https://github.com/felangel/mason/tree/master/packages/mason_cli#publishing-bricks) when you are logged in. This could be used in the future when brickhub is not a closed alpha for testing 😄 

Yes, correct he was talking about that on the twitter spaces back then 👍

**Comment by AbbasMathiew** [comment]
>

**Comment by AbbasMathiew** [comment]
> @AbbasMathiew If the brick code is local then I don't think that would be the case. I think if we change the folder structure for where the brick is located then, yes 😄
> 
> I haven't tried with having a brick on a github repo and use it from there.
> 
> I saw that people would be able to [publish to brickhub](https://github.com/felangel/mason/tree/master/packages/mason_cli#publishing-bricks) when you are logged in. This could be used in the future when brickhub is not a closed alpha for testing 😄
> 
> Yes, correct he was talking about that on the twitter spaces back then 👍

Alright, but we can make use of the bricks in pre-existing projects right? If so we need to add it in the docs, the how-to get the brick and install it on pre-existing project before adding these

**Comment by martinloesethjensen** [comment]
@AbbasMathiew I have added that to the bricks folder [README.md](https://github.com/martinloesethjensen/flutter-template/blob/feature/mason/bricks/README.md) 😄 also just pushed the other bricks README.md

**Review by AbbasMathiew — APPROVED** [review]

**Pull request merged**
