### PR TITLE
fix: Fixed freezed class typo

### PR DESCRIPTION
**Pull request by utpal-barman**
# General

- Fixed a typo for a freezed class which was making an error on the build runner
- Did a run on an iOS simulator which migrated IPHONEOS_DEPLOYMENT_TARGET to 11.0 automatically
- After splash screen it was navigating (pushing) to the screen, but should replace the splash screen
- super.initState() moved on the top of the overridden initState method

# Pull Request (PR) Checklist

- [x] PR title includes Jira ticket reference -- if no ticket available create one if this PR is a fix or feat
- [x] Branch name includes Jira ticket reference (parent ticket and sub-task if available), e.g. 'feat/APP-XXX_Some_Feature' or feat/APP-XXX_APP-XXX_Some_Sub_Task or 'fix/APP-XXX_Some_Fix' or 'refactor/Some_Refactoring'
- [x] All PR checks pass and changes under /domain are covered with unit tests
- [x] Jira ticket provides testing infos for QA -- add a comment if needed e.q. for pre-requisites, order of API calls, ...
- [x] When merging this PR the commit message follows [conventional-commits](https://www.conventionalcommits.org/en/v1.0.0/#summary), e.g. 'feat(some optional epic): add some feature (APP-XXX) (#XXX)'

### CODE REVIEW

**Review by nivisi — APPROVED** [review]

**Review by hassan-saleh-ml — APPROVED** [review]

**Comment by utpal-barman** [comment]
as I changed the minimum deployment target and os version to 12.0, requesting for approval again

**Review by hassan-saleh-ml — APPROVED** [review]
Should we also change some Android stuff like gradle and kotlin versions?

**Comment by utpal-barman** [comment]
Good point, let me check the android one as well

**Comment by utpal-barman** [comment]
I tried to upgrade the version (suggested by flutter create .) but looks like Nstack is complaining

```sh
* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':nstack' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50
```

so we need this PR to be merged https://github.com/nstack-io/flutter-sdk/pull/57/files

We need to keep the current grade for now in this template, later we can do this in a separate PR

**Comment by nivisi** [comment]
Agree. Let's do this in a separate PR. We should have updated the iOS stuff separately as well 😄

**Review by nivisi — APPROVED** [review]

**Pull request merged**
